### ISSUE TITLE
Error in sprtinf("%s variants to be retained in output", length(VAR_id)) :    could not find function "sprtinf"

### ISSUE THREAD

**Issue by flkick** [KennaLab/rvat#4]
https://github.com/KennaLab/rvat/blob/ca6da3e36bc8c95e06d8cc047e8787df7828497d/R/gdb.R#L396C25-L396C32
In the function writeVcf there is a typo in line 396, causing the error as stated in the title when running the VAR_id option.

**Comment by pjhop** [comment]
Thanks! Solved in commit 6502c18
